language: php
php:
  - '7.0'
  - '5.6'
  - nightly
  - hhvm

install:
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
